"""Oracle vectors for the basic and proof-of-possession schemes from blspy (Chia's C++ library)."""
import hashlib
import blspy
from blspy import BasicSchemeMPL as B, PopSchemeMPL as P, PrivateKey

def seed(i):
    return hashlib.sha256(b"java-bls-chia oracle seed %d" % i).digest()

msgs = [b"", b"\x00", b"abc", bytes(range(32)), b"\xff" * 100]
rows = []
keys = [B.key_gen(seed(i)) for i in range(4)]
for i, sk in enumerate(keys):
    pk = sk.get_g1()
    for j, m in enumerate(msgs):
        rows.append(("basic_sign", bytes(sk).hex(), m.hex(), bytes(B.sign(sk, m)).hex()))
        rows.append(("pop_sign", bytes(sk).hex(), m.hex(), bytes(P.sign(sk, m)).hex()))
    rows.append(("pop_prove", bytes(sk).hex(), "", bytes(P.pop_prove(sk)).hex()))

# Aggregate verification: (scheme, sks, msgs, expected)
def agg_case(scheme, name, sks, ms, sig_override=None):
    sigs = [scheme.sign(k, m) for k, m in zip(sks, ms)]
    agg = scheme.aggregate(sigs) if sig_override is None else sig_override
    ok = scheme.aggregate_verify([k.get_g1() for k in sks], ms, agg)
    rows.append((name, "|".join(bytes(k).hex() for k in sks), "|".join(m.hex() for m in ms),
                 bytes(agg).hex() + ":" + str(ok).lower()))

agg_case(B, "basic_aggregate_verify", keys[:3], msgs[:3])
agg_case(B, "basic_aggregate_verify", keys[:2], [msgs[2], msgs[2]])          # duplicate msg -> false
agg_case(P, "pop_aggregate_verify", keys[:2], [msgs[2], msgs[2]])            # allowed under PoP
agg_case(P, "pop_aggregate_verify", keys, msgs[:4])

# fast_aggregate_verify: (sks, msg, expected)
m = msgs[3]
agg = P.aggregate([P.sign(k, m) for k in keys])
rows.append(("pop_fast_aggregate_verify", "|".join(bytes(k).hex() for k in keys), m.hex(),
             bytes(agg).hex() + ":" + str(P.fast_aggregate_verify([k.get_g1() for k in keys], m, agg)).lower()))
rows.append(("pop_fast_aggregate_verify", "|".join(bytes(k).hex() for k in keys[:3]), m.hex(),
             bytes(agg).hex() + ":" + str(P.fast_aggregate_verify([k.get_g1() for k in keys[:3]], m, agg)).lower()))
# pop_verify negative: proof of key 0 against key 1
rows.append(("pop_verify", bytes(keys[1]).hex(), "", bytes(P.pop_prove(keys[0])).hex() + ":" +
             str(P.pop_verify(keys[1].get_g1(), P.pop_prove(keys[0]))).lower()))

print("# kind,secret_keys,messages,expected  (generated by gen_blspy.py with blspy " + blspy.__version__ if hasattr(blspy, "__version__") else "# kind,secret_keys,messages,expected  (generated by gen_blspy.py with blspy 2.0.3)")
for r in rows:
    print(",".join(r))
